name: Create Pull Request
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create report file
        run: make update-gcloud-version
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update GCloud SDK Version
          author-email: milesmatthias@users.noreply.github.com
          author-name: Miles Matthias
          title: 'Update GCloud SDk'
          body: |
            Updated GCloud SDK Version
          labels: automated pr
          assignees: morgante,aaron-lane,milesmatthias
          reviewers: morgante,aaron-lane,milesmatthias
          branch: create-pull-request/patch-gcloud-version
          branch-suffix: none
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
